package model;
// Generated May 18, 2018 7:24:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="apprendrejlf"
)
public class Menu  implements java.io.Serializable {


     private Integer id;
     private Menu menu;
     private Integer level;
     private Integer order;
     private String name;
     private String url;
     private String icon;
     private Boolean state;
     private Set menus = new HashSet(0);
     private Set roleMenus = new HashSet(0);

    public Menu() {
    }

	
    public Menu(Menu menu) {
        this.menu = menu;
    }
    public Menu(Menu menu, Integer level, Integer order, String name, String url, String icon, Boolean state, Set menus, Set roleMenus) {
       this.menu = menu;
       this.level = level;
       this.order = order;
       this.name = name;
       this.url = url;
       this.icon = icon;
       this.state = state;
       this.menus = menus;
       this.roleMenus = roleMenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_id", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    
    @Column(name="level")
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }

    
    @Column(name="order")
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }

    
    @Column(name="name", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="url", length=120)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="icon", length=30)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getRoleMenus() {
        return this.roleMenus;
    }
    
    public void setRoleMenus(Set roleMenus) {
        this.roleMenus = roleMenus;
    }




}


