package model;
// Generated May 18, 2018 7:24:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="apprendrejlf"
)
public class Role  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Boolean state;
     private Set users = new HashSet(0);
     private Set roleMenus = new HashSet(0);

    public Role() {
        this.id = 0;
    }

    public Role(String name, String description, Boolean state, Set users, Set roleMenus) {
       this.name = name;
       this.description = description;
       this.state = state;
       this.users = users;
       this.roleMenus = roleMenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set getRoleMenus() {
        return this.roleMenus;
    }
    
    public void setRoleMenus(Set roleMenus) {
        this.roleMenus = roleMenus;
    }




}


