package model;
// Generated May 18, 2018 7:24:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="apprendrejlf"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private Role role;
     private String username;
     private String password;
     private String name;
     private String email;
     private Boolean state;
     private String usercreation;
     private Date datecreation;
     private String usermodification;
     private Date datemodification;

    public User() {
        this.id = 0;
        this.role = new Role();
    }

	
    public User(Role role) {
        this.role = role;
    }
    public User(Role role, String username, String password, String name, String email, Boolean state, String usercreation, Date datecreation, String usermodification, Date datemodification) {
       this.role = role;
       this.username = username;
       this.password = password;
       this.name = name;
       this.email = email;
       this.state = state;
       this.usercreation = usercreation;
       this.datecreation = datecreation;
       this.usermodification = usermodification;
       this.datemodification = datemodification;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=80)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

    
    @Column(name="usercreation", length=45)
    public String getUsercreation() {
        return this.usercreation;
    }
    
    public void setUsercreation(String usercreation) {
        this.usercreation = usercreation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datecreation", length=19)
    public Date getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(Date datecreation) {
        this.datecreation = datecreation;
    }

    
    @Column(name="usermodification", length=45)
    public String getUsermodification() {
        return this.usermodification;
    }
    
    public void setUsermodification(String usermodification) {
        this.usermodification = usermodification;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datemodification", length=19)
    public Date getDatemodification() {
        return this.datemodification;
    }
    
    public void setDatemodification(Date datemodification) {
        this.datemodification = datemodification;
    }

}


